# -*- mode: ruby
# vi: set ft=ruby

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define "vm_centos" do |vm_centos|
        vm_centos.vm.box = "centos/7"
        vm_centos.vm.hostname = "centos"
        vm_centos.vm.network :private_network, ip: "192.168.33.23"    
    end

    config.vm.provider "virtualbox" do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", "1024"]
    end
end