- name: "Instala biblioteca python-mysqldb"
  apt: name=python-mysqldb state=latest install_recommends=yes

- name: "Cria /opt/wordpress"
  file: dest=/opt/wordpress mode=755 state=directory owner=www-data