# -*- mode: ruby -*-
# vi: set ft=ruby

VAGRANTFILE_API_VERSION = "2"
BOX_NAME = ENV['VAGRANT_BOX_NAME'] || "bento/centos-7.3"
HOST_NAME = "m1"
IP_ADDRESS = "192.168.10.2"
PLAYBOOK_PATH = "webserver.yml"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define "virtualmachine" do |virtualmachine|
        virtualmachine.vm.box = BOX_NAME
        virtualmachine.vm.hostname = HOST_NAME
        virtualmachine.vm.network :private_network, ip: IP_ADDRESS

        virtualmachine.vm.provision "ansible" do |ansible|
            ansible.playbook = PLAYBOOK_PATH
            ansible.verbose = "vvv"
        end
    end

    config.vm.provider "virtualbox" do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", "1024"]
    end
end
