# -*- mode: ruby
# vi: set ft=ruby

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "devstack" do |devstack|
    devstack.vm.box = "bento/centos-7.2"
    devstack.vm.hostname = "devstack"
    devstack.vm.network :private_network, ip: "192.168.33.2"

    devstack.vm.provision "ansible" do |ansible|
      ansible.playbook = "devstack.yml"
      # ansible.verbose = "vvv"
    end
  end

  config.vm.provider "virtualbox" do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", "8192", "--cpus", "4"]
  end
end
