# -*- mode: ruby -*-
# vi: set ft=ruby

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define "testvm" do |testvm|
        testvm.vm.box = "ubuntu/trusty64"
        testvm.vm.network :private_network, ip: "192.168.33.21"
    end

    config.vm.provider "virtualbox" do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", "1024"]
    end
end