# -*- mode: ruby -*-
# vi: set ft=ruby

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define "blogvm" do |blogvm|
        blogvm.vm.box = "ubuntu/trusty64"
        blogvm.vm.hostname = "blogvm"
        blogvm.vm.network :private_network, ip: "192.168.33.22"
        
        blogvm.vm.provision "ansible" do |ansible|
            ansible.playbook = "blog.yml"
            ansible.verbose = "vvv"
        end
    end

    config.vm.provider "virtualbox" do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", "1024"]
    end
end